/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AudioDevice {
  'output' : string,
  'manufacturer' : string,
  'isWireless' : boolean,
  'description' : string,
  'isStereo' : boolean,
  'deviceType' : string,
}
export interface Battery {
  'voltage' : number,
  'model' : string,
  'type' : string,
  'connector' : string,
  'capacity' : bigint,
}
export interface Branding {
  'productLogo' : string,
  'productName' : string,
  'companyLogo' : string,
  'companyName' : string,
}
export interface Camera {
  'id' : bigint,
  'hasZoom' : boolean,
  'type' : string,
  'pixelResolution' : string,
  'hasAutofocus' : boolean,
  'lensType' : string,
}
export interface DeviceBlueprint {
  'weight' : bigint,
  'impedance' : bigint,
  'name' : string,
  'rams' : Array<RAM>,
  'protection' : Protection,
  'deviceSlots' : Array<DeviceSlot>,
  'resistanceRating' : string,
  'processingUnit' : ProcessingUnit,
  'connections' : DeviceConnections,
  'wirelessPowerTransfer' : Array<string>,
  'coating' : string,
  'finalized' : boolean,
  'category' : DeviceCategory,
  'comfortRating' : string,
  'display' : DisplayUnit,
  'motherboard' : Motherboard,
  'ports' : Array<string>,
  'certifications' : Array<string>,
  'price' : bigint,
  'battery' : Battery,
  'technologyRatingSystem' : string,
  'storages' : Array<Storage>,
  'audioDevices' : Array<AudioDevice>,
  'cameras' : Array<Camera>,
}
export type DeviceBlueprintId = bigint;
export type DeviceCategory = { 'singleCategory' : string } |
  { 'categoryList' : Array<string> };
export interface DeviceConnections {
  'wirelessConnections' : Array<WirelessConnection>,
  'portConnections' : Array<PortConnection>,
  'smartConnections' : Array<SmartConnection>,
}
export interface DeviceSlot {
  'maxCapacity' : bigint,
  'version' : string,
  'slotType' : string,
}
export interface DisplayUnit {
  'height' : bigint,
  'manufacturer' : string,
  'displayType' : string,
  'frameRate' : bigint,
  'brightness' : bigint,
  'details' : string,
  'energyConsumption' : [] | [bigint],
  'width' : bigint,
}
export interface GameState {
  'cash' : bigint,
  'difficulty' : string,
  'researchedTechs' : Array<string>,
  'products' : Array<string>,
}
export interface Motherboard {
  'sockets' : Array<string>,
  'interfaces' : Array<string>,
}
export interface PlayerResearch {
  'daysActive' : bigint,
  'totalSpent' : bigint,
  'researchId' : string,
  'researchLevel' : bigint,
  'researchState' : bigint,
}
export interface PortConnection {
  'features' : Array<string>,
  'manufacturer' : string,
  'count' : bigint,
  'compatibility' : Array<string>,
  'version' : string,
  'supportedStandards' : Array<string>,
  'compatibilityRequirements' : Array<string>,
  'supportedProtocols' : Array<string>,
  'portType' : string,
  'physicalFormFactor' : string,
}
export interface ProcessingUnit {
  'manufacturer' : string,
  'clockSpeed' : [] | [bigint],
  'coreType' : string,
  'standards' : Array<string>,
  'name' : string,
  'cores' : bigint,
  'manufacturingYear' : [] | [bigint],
  'architecture' : string,
  'energyConsumption' : [] | [bigint],
}
export interface Protection {
  'mechanisms' : Array<ProtectionMechanism>,
  'protectionRating' : string,
}
export interface ProtectionMechanism {
  'mechanismType' : string,
  'waterproofCertification' : string,
  'fingerprintResistance' : boolean,
  'structuralFeatures' : Array<string>,
  'additionalFeatures' : Array<string>,
  'layerCount' : bigint,
  'material' : string,
}
export interface RAM {
  'id' : bigint,
  'manufacturer' : string,
  'clockSpeed' : bigint,
  'type' : string,
  'description' : string,
  'capacity' : bigint,
  'modules' : bigint,
}
export interface ReleasedProduct {
  'features' : Array<string>,
  'name' : string,
  'year' : bigint,
  'productId' : string,
  'sales' : bigint,
  'category' : string,
  'rating' : number,
  'price' : bigint,
}
export interface Requirements {
  'cash' : [] | [bigint],
  'researchedTechnologies' : [] | [Array<string>],
}
export type ResearchStatus = { 'notStarted' : null } |
  { 'completed' : null } |
  { 'inProgress' : bigint };
export interface SaveSlot {
  'id' : string,
  'name' : string,
  'lastModified' : bigint,
}
export interface SavedGame {
  'saveId' : string,
  'name' : string,
  'lastModified' : bigint,
  'gameState' : GameState,
  'branding' : Branding,
  'releasedProducts' : Array<ReleasedProduct>,
  'storeNetwork' : StoreNetwork,
}
export interface SmartConnection {
  'frequencyBand' : string,
  'manufacturer' : string,
  'transportProtocol' : string,
  'smartFeatures' : Array<string>,
  'rangeInMeters' : bigint,
  'interfaceType' : string,
  'encryptionType' : string,
  'standard' : string,
}
export interface Storage {
  'id' : bigint,
  'manufacturer' : string,
  'writeSpeed' : [] | [bigint],
  'cacheSize' : [] | [bigint],
  'name' : string,
  'type' : string,
  'readSpeed' : [] | [bigint],
  'description' : string,
  'energyConsumption' : bigint,
  'endurance' : [] | [bigint],
  'capacity' : bigint,
  'isSolidState' : [] | [boolean],
}
export interface Store {
  'country' : string,
  'employees' : bigint,
  'inventoryCapacity' : bigint,
  'establishmentDate' : bigint,
  'storeName' : string,
  'location' : string,
}
export interface StoreNetwork {
  'stores' : Array<Store>,
  'productAttractionBonus' : bigint,
  'productivityBonus' : bigint,
}
export interface Technology {
  'status' : ResearchStatus,
  'effectedTestProps' : Array<string>,
  'isCompleted' : boolean,
  'cost' : bigint,
  'description' : string,
  'researchDate' : [] | [bigint],
  'researchName' : string,
  'researchTime' : bigint,
  'researchId' : string,
  'category' : string,
  'price' : bigint,
  'requirements' : [] | [Requirements],
}
export interface UserProfile {
  'name' : string,
  'totalPlayTime' : bigint,
  'preferredDifficulty' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WirelessConnection {
  'connectionName' : string,
  'supportedStandards' : Array<string>,
  'maxUploadSpeed' : bigint,
  'maxDownloadSpeed' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReleasedProductToSave' : ActorMethod<
    [string, ReleasedProduct],
    undefined
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'completeResearchEntry' : ActorMethod<[PlayerResearch], undefined>,
  'createDeviceBlueprint' : ActorMethod<[DeviceBlueprint], DeviceBlueprintId>,
  'getActiveTechnologyResearch' : ActorMethod<[], [] | [PlayerResearch]>,
  'getAllDeviceBlueprints' : ActorMethod<[], Array<DeviceBlueprint>>,
  'getAllDeviceCategories' : ActorMethod<[], DeviceCategory>,
  'getAllReleasedProducts' : ActorMethod<[], Array<ReleasedProduct>>,
  'getAllTechnologies' : ActorMethod<[], Array<Technology>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSaveSlotInfos' : ActorMethod<[], Array<SaveSlot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'loadSaveSlot' : ActorMethod<[string], [] | [SavedGame]>,
  'processInput' : ActorMethod<[Uint8Array], string>,
  'renameSaveSlot' : ActorMethod<[string, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGameToSlot' : ActorMethod<[SavedGame], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];