/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ReleasedProduct = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'year' : IDL.Nat,
  'productId' : IDL.Text,
  'sales' : IDL.Nat,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlayerResearch = IDL.Record({
  'daysActive' : IDL.Nat,
  'totalSpent' : IDL.Nat,
  'researchId' : IDL.Text,
  'researchLevel' : IDL.Nat,
  'researchState' : IDL.Nat,
});
export const RAM = IDL.Record({
  'id' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'clockSpeed' : IDL.Nat,
  'type' : IDL.Text,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
  'modules' : IDL.Nat,
});
export const ProtectionMechanism = IDL.Record({
  'mechanismType' : IDL.Text,
  'waterproofCertification' : IDL.Text,
  'fingerprintResistance' : IDL.Bool,
  'structuralFeatures' : IDL.Vec(IDL.Text),
  'additionalFeatures' : IDL.Vec(IDL.Text),
  'layerCount' : IDL.Nat,
  'material' : IDL.Text,
});
export const Protection = IDL.Record({
  'mechanisms' : IDL.Vec(ProtectionMechanism),
  'protectionRating' : IDL.Text,
});
export const DeviceSlot = IDL.Record({
  'maxCapacity' : IDL.Nat,
  'version' : IDL.Text,
  'slotType' : IDL.Text,
});
export const ProcessingUnit = IDL.Record({
  'manufacturer' : IDL.Text,
  'clockSpeed' : IDL.Opt(IDL.Nat),
  'coreType' : IDL.Text,
  'standards' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'cores' : IDL.Nat,
  'manufacturingYear' : IDL.Opt(IDL.Nat),
  'architecture' : IDL.Text,
  'energyConsumption' : IDL.Opt(IDL.Nat),
});
export const WirelessConnection = IDL.Record({
  'connectionName' : IDL.Text,
  'supportedStandards' : IDL.Vec(IDL.Text),
  'maxUploadSpeed' : IDL.Nat,
  'maxDownloadSpeed' : IDL.Nat,
});
export const PortConnection = IDL.Record({
  'features' : IDL.Vec(IDL.Text),
  'manufacturer' : IDL.Text,
  'count' : IDL.Nat,
  'compatibility' : IDL.Vec(IDL.Text),
  'version' : IDL.Text,
  'supportedStandards' : IDL.Vec(IDL.Text),
  'compatibilityRequirements' : IDL.Vec(IDL.Text),
  'supportedProtocols' : IDL.Vec(IDL.Text),
  'portType' : IDL.Text,
  'physicalFormFactor' : IDL.Text,
});
export const SmartConnection = IDL.Record({
  'frequencyBand' : IDL.Text,
  'manufacturer' : IDL.Text,
  'transportProtocol' : IDL.Text,
  'smartFeatures' : IDL.Vec(IDL.Text),
  'rangeInMeters' : IDL.Nat,
  'interfaceType' : IDL.Text,
  'encryptionType' : IDL.Text,
  'standard' : IDL.Text,
});
export const DeviceConnections = IDL.Record({
  'wirelessConnections' : IDL.Vec(WirelessConnection),
  'portConnections' : IDL.Vec(PortConnection),
  'smartConnections' : IDL.Vec(SmartConnection),
});
export const FoldableCharacteristics = IDL.Record({
  'weight' : IDL.Nat,
  'wirelessChargingSupport' : IDL.Bool,
  'hingeMaterial' : IDL.Text,
  'foldAngle' : IDL.Float64,
  'hingeDurability' : IDL.Nat,
  'facePrintResistance' : IDL.Int,
  'thickness' : IDL.Float64,
  'magneticLock' : IDL.Bool,
  'resistanceRating' : IDL.Text,
  'fingerprintResistance' : IDL.Bool,
  'multiAngleSupport' : IDL.Bool,
  'outerDisplaySize' : IDL.Opt(IDL.Float64),
  'hingeType' : IDL.Text,
  'finalized' : IDL.Bool,
  'coatingType' : IDL.Text,
  'shockproofRating' : IDL.Text,
  'displayTechnology' : IDL.Text,
  'outerDisplay' : IDL.Bool,
  'creaseVisibility' : IDL.Nat,
  'price' : IDL.Nat,
  'foldType' : IDL.Text,
  'waterproofRating' : IDL.Text,
});
export const DeviceCategory = IDL.Variant({
  'singleCategory' : IDL.Text,
  'categoryList' : IDL.Vec(IDL.Text),
});
export const DisplayUnit = IDL.Record({
  'height' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'displayType' : IDL.Text,
  'frameRate' : IDL.Nat,
  'brightness' : IDL.Nat,
  'details' : IDL.Text,
  'energyConsumption' : IDL.Opt(IDL.Nat),
  'width' : IDL.Nat,
});
export const Motherboard = IDL.Record({
  'sockets' : IDL.Vec(IDL.Text),
  'interfaces' : IDL.Vec(IDL.Text),
});
export const Battery = IDL.Record({
  'voltage' : IDL.Float64,
  'model' : IDL.Text,
  'type' : IDL.Text,
  'connector' : IDL.Text,
  'capacity' : IDL.Nat,
});
export const Storage = IDL.Record({
  'id' : IDL.Nat,
  'manufacturer' : IDL.Text,
  'writeSpeed' : IDL.Opt(IDL.Nat),
  'cacheSize' : IDL.Opt(IDL.Nat),
  'name' : IDL.Text,
  'type' : IDL.Text,
  'readSpeed' : IDL.Opt(IDL.Nat),
  'description' : IDL.Text,
  'energyConsumption' : IDL.Nat,
  'endurance' : IDL.Opt(IDL.Nat),
  'capacity' : IDL.Nat,
  'isSolidState' : IDL.Opt(IDL.Bool),
});
export const AudioDevice = IDL.Record({
  'output' : IDL.Text,
  'manufacturer' : IDL.Text,
  'isWireless' : IDL.Bool,
  'description' : IDL.Text,
  'isStereo' : IDL.Bool,
  'deviceType' : IDL.Text,
});
export const Camera = IDL.Record({
  'id' : IDL.Nat,
  'hasZoom' : IDL.Bool,
  'type' : IDL.Text,
  'pixelResolution' : IDL.Text,
  'hasAutofocus' : IDL.Bool,
  'lensType' : IDL.Text,
});
export const DeviceBlueprint = IDL.Record({
  'weight' : IDL.Nat,
  'impedance' : IDL.Nat,
  'name' : IDL.Text,
  'rams' : IDL.Vec(RAM),
  'protection' : Protection,
  'deviceSlots' : IDL.Vec(DeviceSlot),
  'resistanceRating' : IDL.Text,
  'processingUnit' : ProcessingUnit,
  'connections' : DeviceConnections,
  'wirelessPowerTransfer' : IDL.Vec(IDL.Text),
  'foldableCharacteristics' : IDL.Opt(FoldableCharacteristics),
  'coating' : IDL.Text,
  'finalized' : IDL.Bool,
  'category' : DeviceCategory,
  'comfortRating' : IDL.Text,
  'display' : DisplayUnit,
  'motherboard' : Motherboard,
  'ports' : IDL.Vec(IDL.Text),
  'certifications' : IDL.Vec(IDL.Text),
  'price' : IDL.Nat,
  'battery' : Battery,
  'technologyRatingSystem' : IDL.Text,
  'storages' : IDL.Vec(Storage),
  'audioDevices' : IDL.Vec(AudioDevice),
  'cameras' : IDL.Vec(Camera),
});
export const DeviceBlueprintId = IDL.Nat;
export const BlueprintSubmissionResult = IDL.Variant({
  'success' : DeviceBlueprintId,
  'premiumFeatureRequired' : IDL.Null,
});
export const ResearchStatus = IDL.Variant({
  'notStarted' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Nat,
});
export const Requirements = IDL.Record({
  'cash' : IDL.Opt(IDL.Nat),
  'researchedTechnologies' : IDL.Opt(IDL.Vec(IDL.Text)),
});
export const Technology = IDL.Record({
  'status' : ResearchStatus,
  'effectedTestProps' : IDL.Vec(IDL.Text),
  'isCompleted' : IDL.Bool,
  'cost' : IDL.Nat,
  'description' : IDL.Text,
  'researchDate' : IDL.Opt(IDL.Nat),
  'researchName' : IDL.Text,
  'researchTime' : IDL.Nat,
  'researchId' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'requirements' : IDL.Opt(Requirements),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'totalPlayTime' : IDL.Nat,
  'preferredDifficulty' : IDL.Opt(IDL.Text),
});
export const SaveSlot = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'lastModified' : IDL.Int,
});
export const GameState = IDL.Record({
  'cash' : IDL.Nat,
  'difficulty' : IDL.Text,
  'researchedTechs' : IDL.Vec(IDL.Text),
  'products' : IDL.Vec(IDL.Text),
});
export const Branding = IDL.Record({
  'productLogo' : IDL.Text,
  'productName' : IDL.Text,
  'companyLogo' : IDL.Text,
  'companyName' : IDL.Text,
});
export const Store = IDL.Record({
  'country' : IDL.Text,
  'employees' : IDL.Nat,
  'inventoryCapacity' : IDL.Nat,
  'establishmentDate' : IDL.Nat,
  'storeName' : IDL.Text,
  'location' : IDL.Text,
});
export const StoreNetwork = IDL.Record({
  'stores' : IDL.Vec(Store),
  'productAttractionBonus' : IDL.Nat,
  'productivityBonus' : IDL.Nat,
});
export const SavedGame = IDL.Record({
  'saveId' : IDL.Text,
  'name' : IDL.Text,
  'lastModified' : IDL.Nat,
  'triggeredEvents' : IDL.Vec(IDL.Text),
  'gameState' : GameState,
  'branding' : Branding,
  'releasedProducts' : IDL.Vec(ReleasedProduct),
  'storeNetwork' : StoreNetwork,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'activatePremiumUnlock' : IDL.Func([], [], []),
  'addReleasedProductToSave' : IDL.Func([IDL.Text, ReleasedProduct], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'completeResearchEntry' : IDL.Func([PlayerResearch], [], []),
  'createDeviceBlueprint' : IDL.Func(
      [DeviceBlueprint],
      [BlueprintSubmissionResult],
      [],
    ),
  'getActiveTechnologyResearch' : IDL.Func(
      [],
      [IDL.Opt(PlayerResearch)],
      ['query'],
    ),
  'getAllDeviceBlueprints' : IDL.Func(
      [],
      [IDL.Vec(DeviceBlueprint)],
      ['query'],
    ),
  'getAllDeviceCategories' : IDL.Func([], [DeviceCategory], ['query']),
  'getAllReleasedProducts' : IDL.Func(
      [],
      [IDL.Vec(ReleasedProduct)],
      ['query'],
    ),
  'getAllTechnologies' : IDL.Func([], [IDL.Vec(Technology)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSaveSlotInfos' : IDL.Func([], [IDL.Vec(SaveSlot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasPremiumUnlock' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'loadSaveSlot' : IDL.Func([IDL.Text], [IDL.Opt(SavedGame)], []),
  'processInput' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
  'renameSaveSlot' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGameToSlot' : IDL.Func([SavedGame], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ReleasedProduct = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'year' : IDL.Nat,
    'productId' : IDL.Text,
    'sales' : IDL.Nat,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlayerResearch = IDL.Record({
    'daysActive' : IDL.Nat,
    'totalSpent' : IDL.Nat,
    'researchId' : IDL.Text,
    'researchLevel' : IDL.Nat,
    'researchState' : IDL.Nat,
  });
  const RAM = IDL.Record({
    'id' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'clockSpeed' : IDL.Nat,
    'type' : IDL.Text,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
    'modules' : IDL.Nat,
  });
  const ProtectionMechanism = IDL.Record({
    'mechanismType' : IDL.Text,
    'waterproofCertification' : IDL.Text,
    'fingerprintResistance' : IDL.Bool,
    'structuralFeatures' : IDL.Vec(IDL.Text),
    'additionalFeatures' : IDL.Vec(IDL.Text),
    'layerCount' : IDL.Nat,
    'material' : IDL.Text,
  });
  const Protection = IDL.Record({
    'mechanisms' : IDL.Vec(ProtectionMechanism),
    'protectionRating' : IDL.Text,
  });
  const DeviceSlot = IDL.Record({
    'maxCapacity' : IDL.Nat,
    'version' : IDL.Text,
    'slotType' : IDL.Text,
  });
  const ProcessingUnit = IDL.Record({
    'manufacturer' : IDL.Text,
    'clockSpeed' : IDL.Opt(IDL.Nat),
    'coreType' : IDL.Text,
    'standards' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'cores' : IDL.Nat,
    'manufacturingYear' : IDL.Opt(IDL.Nat),
    'architecture' : IDL.Text,
    'energyConsumption' : IDL.Opt(IDL.Nat),
  });
  const WirelessConnection = IDL.Record({
    'connectionName' : IDL.Text,
    'supportedStandards' : IDL.Vec(IDL.Text),
    'maxUploadSpeed' : IDL.Nat,
    'maxDownloadSpeed' : IDL.Nat,
  });
  const PortConnection = IDL.Record({
    'features' : IDL.Vec(IDL.Text),
    'manufacturer' : IDL.Text,
    'count' : IDL.Nat,
    'compatibility' : IDL.Vec(IDL.Text),
    'version' : IDL.Text,
    'supportedStandards' : IDL.Vec(IDL.Text),
    'compatibilityRequirements' : IDL.Vec(IDL.Text),
    'supportedProtocols' : IDL.Vec(IDL.Text),
    'portType' : IDL.Text,
    'physicalFormFactor' : IDL.Text,
  });
  const SmartConnection = IDL.Record({
    'frequencyBand' : IDL.Text,
    'manufacturer' : IDL.Text,
    'transportProtocol' : IDL.Text,
    'smartFeatures' : IDL.Vec(IDL.Text),
    'rangeInMeters' : IDL.Nat,
    'interfaceType' : IDL.Text,
    'encryptionType' : IDL.Text,
    'standard' : IDL.Text,
  });
  const DeviceConnections = IDL.Record({
    'wirelessConnections' : IDL.Vec(WirelessConnection),
    'portConnections' : IDL.Vec(PortConnection),
    'smartConnections' : IDL.Vec(SmartConnection),
  });
  const FoldableCharacteristics = IDL.Record({
    'weight' : IDL.Nat,
    'wirelessChargingSupport' : IDL.Bool,
    'hingeMaterial' : IDL.Text,
    'foldAngle' : IDL.Float64,
    'hingeDurability' : IDL.Nat,
    'facePrintResistance' : IDL.Int,
    'thickness' : IDL.Float64,
    'magneticLock' : IDL.Bool,
    'resistanceRating' : IDL.Text,
    'fingerprintResistance' : IDL.Bool,
    'multiAngleSupport' : IDL.Bool,
    'outerDisplaySize' : IDL.Opt(IDL.Float64),
    'hingeType' : IDL.Text,
    'finalized' : IDL.Bool,
    'coatingType' : IDL.Text,
    'shockproofRating' : IDL.Text,
    'displayTechnology' : IDL.Text,
    'outerDisplay' : IDL.Bool,
    'creaseVisibility' : IDL.Nat,
    'price' : IDL.Nat,
    'foldType' : IDL.Text,
    'waterproofRating' : IDL.Text,
  });
  const DeviceCategory = IDL.Variant({
    'singleCategory' : IDL.Text,
    'categoryList' : IDL.Vec(IDL.Text),
  });
  const DisplayUnit = IDL.Record({
    'height' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'displayType' : IDL.Text,
    'frameRate' : IDL.Nat,
    'brightness' : IDL.Nat,
    'details' : IDL.Text,
    'energyConsumption' : IDL.Opt(IDL.Nat),
    'width' : IDL.Nat,
  });
  const Motherboard = IDL.Record({
    'sockets' : IDL.Vec(IDL.Text),
    'interfaces' : IDL.Vec(IDL.Text),
  });
  const Battery = IDL.Record({
    'voltage' : IDL.Float64,
    'model' : IDL.Text,
    'type' : IDL.Text,
    'connector' : IDL.Text,
    'capacity' : IDL.Nat,
  });
  const Storage = IDL.Record({
    'id' : IDL.Nat,
    'manufacturer' : IDL.Text,
    'writeSpeed' : IDL.Opt(IDL.Nat),
    'cacheSize' : IDL.Opt(IDL.Nat),
    'name' : IDL.Text,
    'type' : IDL.Text,
    'readSpeed' : IDL.Opt(IDL.Nat),
    'description' : IDL.Text,
    'energyConsumption' : IDL.Nat,
    'endurance' : IDL.Opt(IDL.Nat),
    'capacity' : IDL.Nat,
    'isSolidState' : IDL.Opt(IDL.Bool),
  });
  const AudioDevice = IDL.Record({
    'output' : IDL.Text,
    'manufacturer' : IDL.Text,
    'isWireless' : IDL.Bool,
    'description' : IDL.Text,
    'isStereo' : IDL.Bool,
    'deviceType' : IDL.Text,
  });
  const Camera = IDL.Record({
    'id' : IDL.Nat,
    'hasZoom' : IDL.Bool,
    'type' : IDL.Text,
    'pixelResolution' : IDL.Text,
    'hasAutofocus' : IDL.Bool,
    'lensType' : IDL.Text,
  });
  const DeviceBlueprint = IDL.Record({
    'weight' : IDL.Nat,
    'impedance' : IDL.Nat,
    'name' : IDL.Text,
    'rams' : IDL.Vec(RAM),
    'protection' : Protection,
    'deviceSlots' : IDL.Vec(DeviceSlot),
    'resistanceRating' : IDL.Text,
    'processingUnit' : ProcessingUnit,
    'connections' : DeviceConnections,
    'wirelessPowerTransfer' : IDL.Vec(IDL.Text),
    'foldableCharacteristics' : IDL.Opt(FoldableCharacteristics),
    'coating' : IDL.Text,
    'finalized' : IDL.Bool,
    'category' : DeviceCategory,
    'comfortRating' : IDL.Text,
    'display' : DisplayUnit,
    'motherboard' : Motherboard,
    'ports' : IDL.Vec(IDL.Text),
    'certifications' : IDL.Vec(IDL.Text),
    'price' : IDL.Nat,
    'battery' : Battery,
    'technologyRatingSystem' : IDL.Text,
    'storages' : IDL.Vec(Storage),
    'audioDevices' : IDL.Vec(AudioDevice),
    'cameras' : IDL.Vec(Camera),
  });
  const DeviceBlueprintId = IDL.Nat;
  const BlueprintSubmissionResult = IDL.Variant({
    'success' : DeviceBlueprintId,
    'premiumFeatureRequired' : IDL.Null,
  });
  const ResearchStatus = IDL.Variant({
    'notStarted' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Nat,
  });
  const Requirements = IDL.Record({
    'cash' : IDL.Opt(IDL.Nat),
    'researchedTechnologies' : IDL.Opt(IDL.Vec(IDL.Text)),
  });
  const Technology = IDL.Record({
    'status' : ResearchStatus,
    'effectedTestProps' : IDL.Vec(IDL.Text),
    'isCompleted' : IDL.Bool,
    'cost' : IDL.Nat,
    'description' : IDL.Text,
    'researchDate' : IDL.Opt(IDL.Nat),
    'researchName' : IDL.Text,
    'researchTime' : IDL.Nat,
    'researchId' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'requirements' : IDL.Opt(Requirements),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'totalPlayTime' : IDL.Nat,
    'preferredDifficulty' : IDL.Opt(IDL.Text),
  });
  const SaveSlot = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'lastModified' : IDL.Int,
  });
  const GameState = IDL.Record({
    'cash' : IDL.Nat,
    'difficulty' : IDL.Text,
    'researchedTechs' : IDL.Vec(IDL.Text),
    'products' : IDL.Vec(IDL.Text),
  });
  const Branding = IDL.Record({
    'productLogo' : IDL.Text,
    'productName' : IDL.Text,
    'companyLogo' : IDL.Text,
    'companyName' : IDL.Text,
  });
  const Store = IDL.Record({
    'country' : IDL.Text,
    'employees' : IDL.Nat,
    'inventoryCapacity' : IDL.Nat,
    'establishmentDate' : IDL.Nat,
    'storeName' : IDL.Text,
    'location' : IDL.Text,
  });
  const StoreNetwork = IDL.Record({
    'stores' : IDL.Vec(Store),
    'productAttractionBonus' : IDL.Nat,
    'productivityBonus' : IDL.Nat,
  });
  const SavedGame = IDL.Record({
    'saveId' : IDL.Text,
    'name' : IDL.Text,
    'lastModified' : IDL.Nat,
    'triggeredEvents' : IDL.Vec(IDL.Text),
    'gameState' : GameState,
    'branding' : Branding,
    'releasedProducts' : IDL.Vec(ReleasedProduct),
    'storeNetwork' : StoreNetwork,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'activatePremiumUnlock' : IDL.Func([], [], []),
    'addReleasedProductToSave' : IDL.Func([IDL.Text, ReleasedProduct], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'completeResearchEntry' : IDL.Func([PlayerResearch], [], []),
    'createDeviceBlueprint' : IDL.Func(
        [DeviceBlueprint],
        [BlueprintSubmissionResult],
        [],
      ),
    'getActiveTechnologyResearch' : IDL.Func(
        [],
        [IDL.Opt(PlayerResearch)],
        ['query'],
      ),
    'getAllDeviceBlueprints' : IDL.Func(
        [],
        [IDL.Vec(DeviceBlueprint)],
        ['query'],
      ),
    'getAllDeviceCategories' : IDL.Func([], [DeviceCategory], ['query']),
    'getAllReleasedProducts' : IDL.Func(
        [],
        [IDL.Vec(ReleasedProduct)],
        ['query'],
      ),
    'getAllTechnologies' : IDL.Func([], [IDL.Vec(Technology)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSaveSlotInfos' : IDL.Func([], [IDL.Vec(SaveSlot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasPremiumUnlock' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'loadSaveSlot' : IDL.Func([IDL.Text], [IDL.Opt(SavedGame)], []),
    'processInput' : IDL.Func([IDL.Vec(IDL.Nat8)], [IDL.Text], []),
    'renameSaveSlot' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGameToSlot' : IDL.Func([SavedGame], [], []),
  });
};

export const init = ({ IDL }) => { return []; };