/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StoreNetwork {
    stores: Array<Store>;
    productAttractionBonus: bigint;
    productivityBonus: bigint;
}
export interface Requirements {
    cash?: bigint;
    researchedTechnologies?: Array<string>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Protection {
    mechanisms: Array<ProtectionMechanism>;
    protectionRating: string;
}
export interface Motherboard {
    sockets: Array<string>;
    interfaces: Array<string>;
}
export interface DisplayUnit {
    height: bigint;
    manufacturer: string;
    displayType: string;
    frameRate: bigint;
    brightness: bigint;
    details: string;
    energyConsumption?: bigint;
    width: bigint;
}
export interface SaveSlot {
    id: string;
    name: string;
    lastModified: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type ResearchStatus = {
    __kind__: "notStarted";
    notStarted: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "inProgress";
    inProgress: bigint;
};
export interface ReleasedProduct {
    features: Array<string>;
    name: string;
    year: bigint;
    productId: string;
    sales: bigint;
    category: string;
    rating: number;
    price: bigint;
}
export interface SmartConnection {
    frequencyBand: string;
    manufacturer: string;
    transportProtocol: string;
    smartFeatures: Array<string>;
    rangeInMeters: bigint;
    interfaceType: string;
    encryptionType: string;
    standard: string;
}
export interface ProcessingUnit {
    manufacturer: string;
    clockSpeed?: bigint;
    coreType: string;
    standards: Array<string>;
    name: string;
    cores: bigint;
    manufacturingYear?: bigint;
    architecture: string;
    energyConsumption?: bigint;
}
export interface DeviceSlot {
    maxCapacity: bigint;
    version: string;
    slotType: string;
}
export interface PlayerResearch {
    daysActive: bigint;
    totalSpent: bigint;
    researchId: string;
    researchLevel: bigint;
    researchState: bigint;
}
export interface FoldableCharacteristics {
    weight: bigint;
    wirelessChargingSupport: boolean;
    hingeMaterial: string;
    foldAngle: number;
    hingeDurability: bigint;
    facePrintResistance: bigint;
    thickness: number;
    magneticLock: boolean;
    resistanceRating: string;
    fingerprintResistance: boolean;
    multiAngleSupport: boolean;
    outerDisplaySize?: number;
    hingeType: string;
    finalized: boolean;
    coatingType: string;
    shockproofRating: string;
    displayTechnology: string;
    outerDisplay: boolean;
    creaseVisibility: bigint;
    price: bigint;
    foldType: string;
    waterproofRating: string;
}
export interface Battery {
    voltage: number;
    model: string;
    type: string;
    connector: string;
    capacity: bigint;
}
export interface Technology {
    status: ResearchStatus;
    effectedTestProps: Array<string>;
    isCompleted: boolean;
    cost: bigint;
    description: string;
    researchDate?: bigint;
    researchName: string;
    researchTime: bigint;
    researchId: string;
    category: string;
    price: bigint;
    requirements?: Requirements;
}
export interface Storage {
    id: bigint;
    manufacturer: string;
    writeSpeed?: bigint;
    cacheSize?: bigint;
    name: string;
    type: string;
    readSpeed?: bigint;
    description: string;
    energyConsumption: bigint;
    endurance?: bigint;
    capacity: bigint;
    isSolidState?: boolean;
}
export interface PortConnection {
    features: Array<string>;
    manufacturer: string;
    count: bigint;
    compatibility: Array<string>;
    version: string;
    supportedStandards: Array<string>;
    compatibilityRequirements: Array<string>;
    supportedProtocols: Array<string>;
    portType: string;
    physicalFormFactor: string;
}
export interface Store {
    country: string;
    employees: bigint;
    inventoryCapacity: bigint;
    establishmentDate: bigint;
    storeName: string;
    location: string;
}
export interface ProtectionMechanism {
    mechanismType: string;
    waterproofCertification: string;
    fingerprintResistance: boolean;
    structuralFeatures: Array<string>;
    additionalFeatures: Array<string>;
    layerCount: bigint;
    material: string;
}
export interface SavedGame {
    saveId: string;
    name: string;
    lastModified: bigint;
    triggeredEvents: Array<string>;
    gameState: GameState;
    branding: Branding;
    releasedProducts: Array<ReleasedProduct>;
    storeNetwork: StoreNetwork;
}
export type DeviceCategory = {
    __kind__: "singleCategory";
    singleCategory: string;
} | {
    __kind__: "categoryList";
    categoryList: Array<string>;
};
export interface DeviceBlueprint {
    weight: bigint;
    impedance: bigint;
    name: string;
    rams: Array<RAM>;
    protection: Protection;
    deviceSlots: Array<DeviceSlot>;
    resistanceRating: string;
    processingUnit: ProcessingUnit;
    connections: DeviceConnections;
    wirelessPowerTransfer: Array<string>;
    foldableCharacteristics?: FoldableCharacteristics;
    coating: string;
    finalized: boolean;
    category: DeviceCategory;
    comfortRating: string;
    display: DisplayUnit;
    motherboard: Motherboard;
    ports: Array<string>;
    certifications: Array<string>;
    price: bigint;
    battery: Battery;
    technologyRatingSystem: string;
    storages: Array<Storage>;
    audioDevices: Array<AudioDevice>;
    cameras: Array<Camera>;
}
export interface WirelessConnection {
    connectionName: string;
    supportedStandards: Array<string>;
    maxUploadSpeed: bigint;
    maxDownloadSpeed: bigint;
}
export interface GameState {
    cash: bigint;
    difficulty: string;
    researchedTechs: Array<string>;
    products: Array<string>;
}
export type BlueprintSubmissionResult = {
    __kind__: "success";
    success: DeviceBlueprintId;
} | {
    __kind__: "premiumFeatureRequired";
    premiumFeatureRequired: null;
};
export interface RAM {
    id: bigint;
    manufacturer: string;
    clockSpeed: bigint;
    type: string;
    description: string;
    capacity: bigint;
    modules: bigint;
}
export type DeviceBlueprintId = bigint;
export interface AudioDevice {
    output: string;
    manufacturer: string;
    isWireless: boolean;
    description: string;
    isStereo: boolean;
    deviceType: string;
}
export interface DeviceConnections {
    wirelessConnections: Array<WirelessConnection>;
    portConnections: Array<PortConnection>;
    smartConnections: Array<SmartConnection>;
}
export interface Camera {
    id: bigint;
    hasZoom: boolean;
    type: string;
    pixelResolution: string;
    hasAutofocus: boolean;
    lensType: string;
}
export interface Branding {
    productLogo: string;
    productName: string;
    companyLogo: string;
    companyName: string;
}
export interface UserProfile {
    name: string;
    totalPlayTime: bigint;
    preferredDifficulty?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    activatePremiumUnlock(): Promise<void>;
    addReleasedProductToSave(slotId: string, product: ReleasedProduct): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    completeResearchEntry(researchEntry: PlayerResearch): Promise<void>;
    createDeviceBlueprint(blueprint: DeviceBlueprint): Promise<BlueprintSubmissionResult>;
    getActiveTechnologyResearch(): Promise<PlayerResearch | null>;
    getAllDeviceBlueprints(): Promise<Array<DeviceBlueprint>>;
    getAllDeviceCategories(): Promise<DeviceCategory>;
    getAllReleasedProducts(): Promise<Array<ReleasedProduct>>;
    getAllTechnologies(): Promise<Array<Technology>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getSaveSlotInfos(): Promise<Array<SaveSlot>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasPremiumUnlock(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    loadSaveSlot(slotId: string): Promise<SavedGame | null>;
    processInput(inputData: Uint8Array): Promise<string>;
    renameSaveSlot(slotId: string, newName: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveGameToSlot(newSave: SavedGame): Promise<void>;
}
import type { AudioDevice as _AudioDevice, Battery as _Battery, BlueprintSubmissionResult as _BlueprintSubmissionResult, Camera as _Camera, DeviceBlueprint as _DeviceBlueprint, DeviceBlueprintId as _DeviceBlueprintId, DeviceCategory as _DeviceCategory, DeviceConnections as _DeviceConnections, DeviceSlot as _DeviceSlot, DisplayUnit as _DisplayUnit, FoldableCharacteristics as _FoldableCharacteristics, Motherboard as _Motherboard, PlayerResearch as _PlayerResearch, ProcessingUnit as _ProcessingUnit, Protection as _Protection, RAM as _RAM, Requirements as _Requirements, ResearchStatus as _ResearchStatus, SavedGame as _SavedGame, Storage as _Storage, Technology as _Technology, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async activatePremiumUnlock(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.activatePremiumUnlock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.activatePremiumUnlock();
            return result;
        }
    }
    async addReleasedProductToSave(arg0: string, arg1: ReleasedProduct): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReleasedProductToSave(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReleasedProductToSave(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async completeResearchEntry(arg0: PlayerResearch): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeResearchEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeResearchEntry(arg0);
            return result;
        }
    }
    async createDeviceBlueprint(arg0: DeviceBlueprint): Promise<BlueprintSubmissionResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createDeviceBlueprint(to_candid_DeviceBlueprint_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_BlueprintSubmissionResult_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDeviceBlueprint(to_candid_DeviceBlueprint_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_BlueprintSubmissionResult_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getActiveTechnologyResearch(): Promise<PlayerResearch | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveTechnologyResearch();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveTechnologyResearch();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeviceBlueprints(): Promise<Array<DeviceBlueprint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeviceBlueprints();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeviceBlueprints();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeviceCategories(): Promise<DeviceCategory> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeviceCategories();
                return from_candid_DeviceCategory_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeviceCategories();
            return from_candid_DeviceCategory_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReleasedProducts(): Promise<Array<ReleasedProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReleasedProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReleasedProducts();
            return result;
        }
    }
    async getAllTechnologies(): Promise<Array<Technology>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTechnologies();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTechnologies();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSaveSlotInfos(): Promise<Array<SaveSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSaveSlotInfos();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSaveSlotInfos();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasPremiumUnlock(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasPremiumUnlock();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasPremiumUnlock();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async loadSaveSlot(arg0: string): Promise<SavedGame | null> {
        if (this.processError) {
            try {
                const result = await this.actor.loadSaveSlot(arg0);
                return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.loadSaveSlot(arg0);
            return from_candid_opt_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async processInput(arg0: Uint8Array): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.processInput(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.processInput(arg0);
            return result;
        }
    }
    async renameSaveSlot(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.renameSaveSlot(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.renameSaveSlot(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n58(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n58(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveGameToSlot(arg0: SavedGame): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGameToSlot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGameToSlot(arg0);
            return result;
        }
    }
}
function from_candid_BlueprintSubmissionResult_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BlueprintSubmissionResult): BlueprintSubmissionResult {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_DeviceBlueprint_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceBlueprint): DeviceBlueprint {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_DeviceCategory_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeviceCategory): DeviceCategory {
    return from_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function from_candid_DisplayUnit_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DisplayUnit): DisplayUnit {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_FoldableCharacteristics_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoldableCharacteristics): FoldableCharacteristics {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ProcessingUnit_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProcessingUnit): ProcessingUnit {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Requirements_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Requirements): Requirements {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_ResearchStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ResearchStatus): ResearchStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Storage_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Storage): Storage {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Technology_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Technology): Technology {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlayerResearch]): PlayerResearch | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FoldableCharacteristics]): FoldableCharacteristics | null {
    return value.length === 0 ? null : from_candid_FoldableCharacteristics_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Requirements]): Requirements | null {
    return value.length === 0 ? null : from_candid_Requirements_n48(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<string>]): Array<string> | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n52(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SavedGame]): SavedGame | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    impedance: bigint;
    name: string;
    rams: Array<_RAM>;
    protection: _Protection;
    deviceSlots: Array<_DeviceSlot>;
    resistanceRating: string;
    processingUnit: _ProcessingUnit;
    connections: _DeviceConnections;
    wirelessPowerTransfer: Array<string>;
    foldableCharacteristics: [] | [_FoldableCharacteristics];
    coating: string;
    finalized: boolean;
    category: _DeviceCategory;
    comfortRating: string;
    display: _DisplayUnit;
    motherboard: _Motherboard;
    ports: Array<string>;
    certifications: Array<string>;
    price: bigint;
    battery: _Battery;
    technologyRatingSystem: string;
    storages: Array<_Storage>;
    audioDevices: Array<_AudioDevice>;
    cameras: Array<_Camera>;
}): {
    weight: bigint;
    impedance: bigint;
    name: string;
    rams: Array<RAM>;
    protection: Protection;
    deviceSlots: Array<DeviceSlot>;
    resistanceRating: string;
    processingUnit: ProcessingUnit;
    connections: DeviceConnections;
    wirelessPowerTransfer: Array<string>;
    foldableCharacteristics?: FoldableCharacteristics;
    coating: string;
    finalized: boolean;
    category: DeviceCategory;
    comfortRating: string;
    display: DisplayUnit;
    motherboard: Motherboard;
    ports: Array<string>;
    certifications: Array<string>;
    price: bigint;
    battery: Battery;
    technologyRatingSystem: string;
    storages: Array<Storage>;
    audioDevices: Array<AudioDevice>;
    cameras: Array<Camera>;
} {
    return {
        weight: value.weight,
        impedance: value.impedance,
        name: value.name,
        rams: value.rams,
        protection: value.protection,
        deviceSlots: value.deviceSlots,
        resistanceRating: value.resistanceRating,
        processingUnit: from_candid_ProcessingUnit_n29(_uploadFile, _downloadFile, value.processingUnit),
        connections: value.connections,
        wirelessPowerTransfer: value.wirelessPowerTransfer,
        foldableCharacteristics: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.foldableCharacteristics)),
        coating: value.coating,
        finalized: value.finalized,
        category: from_candid_DeviceCategory_n35(_uploadFile, _downloadFile, value.category),
        comfortRating: value.comfortRating,
        display: from_candid_DisplayUnit_n37(_uploadFile, _downloadFile, value.display),
        motherboard: value.motherboard,
        ports: value.ports,
        certifications: value.certifications,
        price: value.price,
        battery: value.battery,
        technologyRatingSystem: value.technologyRatingSystem,
        storages: from_candid_vec_n39(_uploadFile, _downloadFile, value.storages),
        audioDevices: value.audioDevices,
        cameras: value.cameras
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manufacturer: string;
    clockSpeed: [] | [bigint];
    coreType: string;
    standards: Array<string>;
    name: string;
    cores: bigint;
    manufacturingYear: [] | [bigint];
    architecture: string;
    energyConsumption: [] | [bigint];
}): {
    manufacturer: string;
    clockSpeed?: bigint;
    coreType: string;
    standards: Array<string>;
    name: string;
    cores: bigint;
    manufacturingYear?: bigint;
    architecture: string;
    energyConsumption?: bigint;
} {
    return {
        manufacturer: value.manufacturer,
        clockSpeed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.clockSpeed)),
        coreType: value.coreType,
        standards: value.standards,
        name: value.name,
        cores: value.cores,
        manufacturingYear: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.manufacturingYear)),
        architecture: value.architecture,
        energyConsumption: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.energyConsumption))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    wirelessChargingSupport: boolean;
    hingeMaterial: string;
    foldAngle: number;
    hingeDurability: bigint;
    facePrintResistance: bigint;
    thickness: number;
    magneticLock: boolean;
    resistanceRating: string;
    fingerprintResistance: boolean;
    multiAngleSupport: boolean;
    outerDisplaySize: [] | [number];
    hingeType: string;
    finalized: boolean;
    coatingType: string;
    shockproofRating: string;
    displayTechnology: string;
    outerDisplay: boolean;
    creaseVisibility: bigint;
    price: bigint;
    foldType: string;
    waterproofRating: string;
}): {
    weight: bigint;
    wirelessChargingSupport: boolean;
    hingeMaterial: string;
    foldAngle: number;
    hingeDurability: bigint;
    facePrintResistance: bigint;
    thickness: number;
    magneticLock: boolean;
    resistanceRating: string;
    fingerprintResistance: boolean;
    multiAngleSupport: boolean;
    outerDisplaySize?: number;
    hingeType: string;
    finalized: boolean;
    coatingType: string;
    shockproofRating: string;
    displayTechnology: string;
    outerDisplay: boolean;
    creaseVisibility: bigint;
    price: bigint;
    foldType: string;
    waterproofRating: string;
} {
    return {
        weight: value.weight,
        wirelessChargingSupport: value.wirelessChargingSupport,
        hingeMaterial: value.hingeMaterial,
        foldAngle: value.foldAngle,
        hingeDurability: value.hingeDurability,
        facePrintResistance: value.facePrintResistance,
        thickness: value.thickness,
        magneticLock: value.magneticLock,
        resistanceRating: value.resistanceRating,
        fingerprintResistance: value.fingerprintResistance,
        multiAngleSupport: value.multiAngleSupport,
        outerDisplaySize: record_opt_to_undefined(from_candid_opt_n34(_uploadFile, _downloadFile, value.outerDisplaySize)),
        hingeType: value.hingeType,
        finalized: value.finalized,
        coatingType: value.coatingType,
        shockproofRating: value.shockproofRating,
        displayTechnology: value.displayTechnology,
        outerDisplay: value.outerDisplay,
        creaseVisibility: value.creaseVisibility,
        price: value.price,
        foldType: value.foldType,
        waterproofRating: value.waterproofRating
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height: bigint;
    manufacturer: string;
    displayType: string;
    frameRate: bigint;
    brightness: bigint;
    details: string;
    energyConsumption: [] | [bigint];
    width: bigint;
}): {
    height: bigint;
    manufacturer: string;
    displayType: string;
    frameRate: bigint;
    brightness: bigint;
    details: string;
    energyConsumption?: bigint;
    width: bigint;
} {
    return {
        height: value.height,
        manufacturer: value.manufacturer,
        displayType: value.displayType,
        frameRate: value.frameRate,
        brightness: value.brightness,
        details: value.details,
        energyConsumption: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.energyConsumption)),
        width: value.width
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    manufacturer: string;
    writeSpeed: [] | [bigint];
    cacheSize: [] | [bigint];
    name: string;
    type: string;
    readSpeed: [] | [bigint];
    description: string;
    energyConsumption: bigint;
    endurance: [] | [bigint];
    capacity: bigint;
    isSolidState: [] | [boolean];
}): {
    id: bigint;
    manufacturer: string;
    writeSpeed?: bigint;
    cacheSize?: bigint;
    name: string;
    type: string;
    readSpeed?: bigint;
    description: string;
    energyConsumption: bigint;
    endurance?: bigint;
    capacity: bigint;
    isSolidState?: boolean;
} {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        writeSpeed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.writeSpeed)),
        cacheSize: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cacheSize)),
        name: value.name,
        type: value.type,
        readSpeed: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.readSpeed)),
        description: value.description,
        energyConsumption: value.energyConsumption,
        endurance: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.endurance)),
        capacity: value.capacity,
        isSolidState: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.isSolidState))
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ResearchStatus;
    effectedTestProps: Array<string>;
    isCompleted: boolean;
    cost: bigint;
    description: string;
    researchDate: [] | [bigint];
    researchName: string;
    researchTime: bigint;
    researchId: string;
    category: string;
    price: bigint;
    requirements: [] | [_Requirements];
}): {
    status: ResearchStatus;
    effectedTestProps: Array<string>;
    isCompleted: boolean;
    cost: bigint;
    description: string;
    researchDate?: bigint;
    researchName: string;
    researchTime: bigint;
    researchId: string;
    category: string;
    price: bigint;
    requirements?: Requirements;
} {
    return {
        status: from_candid_ResearchStatus_n45(_uploadFile, _downloadFile, value.status),
        effectedTestProps: value.effectedTestProps,
        isCompleted: value.isCompleted,
        cost: value.cost,
        description: value.description,
        researchDate: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.researchDate)),
        researchName: value.researchName,
        researchTime: value.researchTime,
        researchId: value.researchId,
        category: value.category,
        price: value.price,
        requirements: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.requirements))
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: [] | [bigint];
    researchedTechnologies: [] | [Array<string>];
}): {
    cash?: bigint;
    researchedTechnologies?: Array<string>;
} {
    return {
        cash: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.cash)),
        researchedTechnologies: record_opt_to_undefined(from_candid_opt_n50(_uploadFile, _downloadFile, value.researchedTechnologies))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    totalPlayTime: bigint;
    preferredDifficulty: [] | [string];
}): {
    name: string;
    totalPlayTime: bigint;
    preferredDifficulty?: string;
} {
    return {
        name: value.name,
        totalPlayTime: value.totalPlayTime,
        preferredDifficulty: record_opt_to_undefined(from_candid_opt_n54(_uploadFile, _downloadFile, value.preferredDifficulty))
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: _DeviceBlueprintId;
} | {
    premiumFeatureRequired: null;
}): {
    __kind__: "success";
    success: DeviceBlueprintId;
} | {
    __kind__: "premiumFeatureRequired";
    premiumFeatureRequired: null;
} {
    return "success" in value ? {
        __kind__: "success",
        success: value.success
    } : "premiumFeatureRequired" in value ? {
        __kind__: "premiumFeatureRequired",
        premiumFeatureRequired: value.premiumFeatureRequired
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    singleCategory: string;
} | {
    categoryList: Array<string>;
}): {
    __kind__: "singleCategory";
    singleCategory: string;
} | {
    __kind__: "categoryList";
    categoryList: Array<string>;
} {
    return "singleCategory" in value ? {
        __kind__: "singleCategory",
        singleCategory: value.singleCategory
    } : "categoryList" in value ? {
        __kind__: "categoryList",
        categoryList: value.categoryList
    } : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    notStarted: null;
} | {
    completed: null;
} | {
    inProgress: bigint;
}): {
    __kind__: "notStarted";
    notStarted: null;
} | {
    __kind__: "completed";
    completed: null;
} | {
    __kind__: "inProgress";
    inProgress: bigint;
} {
    return "notStarted" in value ? {
        __kind__: "notStarted",
        notStarted: value.notStarted
    } : "completed" in value ? {
        __kind__: "completed",
        completed: value.completed
    } : "inProgress" in value ? {
        __kind__: "inProgress",
        inProgress: value.inProgress
    } : value;
}
function from_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeviceBlueprint>): Array<DeviceBlueprint> {
    return value.map((x)=>from_candid_DeviceBlueprint_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Storage>): Array<Storage> {
    return value.map((x)=>from_candid_Storage_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Technology>): Array<Technology> {
    return value.map((x)=>from_candid_Technology_n43(_uploadFile, _downloadFile, x));
}
function to_candid_DeviceBlueprint_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceBlueprint): _DeviceBlueprint {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_DeviceCategory_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeviceCategory): _DeviceCategory {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function to_candid_DisplayUnit_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DisplayUnit): _DisplayUnit {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_FoldableCharacteristics_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoldableCharacteristics): _FoldableCharacteristics {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_ProcessingUnit_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProcessingUnit): _ProcessingUnit {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_Storage_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Storage): _Storage {
    return to_candid_record_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n59(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    impedance: bigint;
    name: string;
    rams: Array<RAM>;
    protection: Protection;
    deviceSlots: Array<DeviceSlot>;
    resistanceRating: string;
    processingUnit: ProcessingUnit;
    connections: DeviceConnections;
    wirelessPowerTransfer: Array<string>;
    foldableCharacteristics?: FoldableCharacteristics;
    coating: string;
    finalized: boolean;
    category: DeviceCategory;
    comfortRating: string;
    display: DisplayUnit;
    motherboard: Motherboard;
    ports: Array<string>;
    certifications: Array<string>;
    price: bigint;
    battery: Battery;
    technologyRatingSystem: string;
    storages: Array<Storage>;
    audioDevices: Array<AudioDevice>;
    cameras: Array<Camera>;
}): {
    weight: bigint;
    impedance: bigint;
    name: string;
    rams: Array<_RAM>;
    protection: _Protection;
    deviceSlots: Array<_DeviceSlot>;
    resistanceRating: string;
    processingUnit: _ProcessingUnit;
    connections: _DeviceConnections;
    wirelessPowerTransfer: Array<string>;
    foldableCharacteristics: [] | [_FoldableCharacteristics];
    coating: string;
    finalized: boolean;
    category: _DeviceCategory;
    comfortRating: string;
    display: _DisplayUnit;
    motherboard: _Motherboard;
    ports: Array<string>;
    certifications: Array<string>;
    price: bigint;
    battery: _Battery;
    technologyRatingSystem: string;
    storages: Array<_Storage>;
    audioDevices: Array<_AudioDevice>;
    cameras: Array<_Camera>;
} {
    return {
        weight: value.weight,
        impedance: value.impedance,
        name: value.name,
        rams: value.rams,
        protection: value.protection,
        deviceSlots: value.deviceSlots,
        resistanceRating: value.resistanceRating,
        processingUnit: to_candid_ProcessingUnit_n12(_uploadFile, _downloadFile, value.processingUnit),
        connections: value.connections,
        wirelessPowerTransfer: value.wirelessPowerTransfer,
        foldableCharacteristics: value.foldableCharacteristics ? candid_some(to_candid_FoldableCharacteristics_n14(_uploadFile, _downloadFile, value.foldableCharacteristics)) : candid_none(),
        coating: value.coating,
        finalized: value.finalized,
        category: to_candid_DeviceCategory_n16(_uploadFile, _downloadFile, value.category),
        comfortRating: value.comfortRating,
        display: to_candid_DisplayUnit_n18(_uploadFile, _downloadFile, value.display),
        motherboard: value.motherboard,
        ports: value.ports,
        certifications: value.certifications,
        price: value.price,
        battery: value.battery,
        technologyRatingSystem: value.technologyRatingSystem,
        storages: to_candid_vec_n20(_uploadFile, _downloadFile, value.storages),
        audioDevices: value.audioDevices,
        cameras: value.cameras
    };
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manufacturer: string;
    clockSpeed?: bigint;
    coreType: string;
    standards: Array<string>;
    name: string;
    cores: bigint;
    manufacturingYear?: bigint;
    architecture: string;
    energyConsumption?: bigint;
}): {
    manufacturer: string;
    clockSpeed: [] | [bigint];
    coreType: string;
    standards: Array<string>;
    name: string;
    cores: bigint;
    manufacturingYear: [] | [bigint];
    architecture: string;
    energyConsumption: [] | [bigint];
} {
    return {
        manufacturer: value.manufacturer,
        clockSpeed: value.clockSpeed ? candid_some(value.clockSpeed) : candid_none(),
        coreType: value.coreType,
        standards: value.standards,
        name: value.name,
        cores: value.cores,
        manufacturingYear: value.manufacturingYear ? candid_some(value.manufacturingYear) : candid_none(),
        architecture: value.architecture,
        energyConsumption: value.energyConsumption ? candid_some(value.energyConsumption) : candid_none()
    };
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    wirelessChargingSupport: boolean;
    hingeMaterial: string;
    foldAngle: number;
    hingeDurability: bigint;
    facePrintResistance: bigint;
    thickness: number;
    magneticLock: boolean;
    resistanceRating: string;
    fingerprintResistance: boolean;
    multiAngleSupport: boolean;
    outerDisplaySize?: number;
    hingeType: string;
    finalized: boolean;
    coatingType: string;
    shockproofRating: string;
    displayTechnology: string;
    outerDisplay: boolean;
    creaseVisibility: bigint;
    price: bigint;
    foldType: string;
    waterproofRating: string;
}): {
    weight: bigint;
    wirelessChargingSupport: boolean;
    hingeMaterial: string;
    foldAngle: number;
    hingeDurability: bigint;
    facePrintResistance: bigint;
    thickness: number;
    magneticLock: boolean;
    resistanceRating: string;
    fingerprintResistance: boolean;
    multiAngleSupport: boolean;
    outerDisplaySize: [] | [number];
    hingeType: string;
    finalized: boolean;
    coatingType: string;
    shockproofRating: string;
    displayTechnology: string;
    outerDisplay: boolean;
    creaseVisibility: bigint;
    price: bigint;
    foldType: string;
    waterproofRating: string;
} {
    return {
        weight: value.weight,
        wirelessChargingSupport: value.wirelessChargingSupport,
        hingeMaterial: value.hingeMaterial,
        foldAngle: value.foldAngle,
        hingeDurability: value.hingeDurability,
        facePrintResistance: value.facePrintResistance,
        thickness: value.thickness,
        magneticLock: value.magneticLock,
        resistanceRating: value.resistanceRating,
        fingerprintResistance: value.fingerprintResistance,
        multiAngleSupport: value.multiAngleSupport,
        outerDisplaySize: value.outerDisplaySize ? candid_some(value.outerDisplaySize) : candid_none(),
        hingeType: value.hingeType,
        finalized: value.finalized,
        coatingType: value.coatingType,
        shockproofRating: value.shockproofRating,
        displayTechnology: value.displayTechnology,
        outerDisplay: value.outerDisplay,
        creaseVisibility: value.creaseVisibility,
        price: value.price,
        foldType: value.foldType,
        waterproofRating: value.waterproofRating
    };
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    height: bigint;
    manufacturer: string;
    displayType: string;
    frameRate: bigint;
    brightness: bigint;
    details: string;
    energyConsumption?: bigint;
    width: bigint;
}): {
    height: bigint;
    manufacturer: string;
    displayType: string;
    frameRate: bigint;
    brightness: bigint;
    details: string;
    energyConsumption: [] | [bigint];
    width: bigint;
} {
    return {
        height: value.height,
        manufacturer: value.manufacturer,
        displayType: value.displayType,
        frameRate: value.frameRate,
        brightness: value.brightness,
        details: value.details,
        energyConsumption: value.energyConsumption ? candid_some(value.energyConsumption) : candid_none(),
        width: value.width
    };
}
function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    manufacturer: string;
    writeSpeed?: bigint;
    cacheSize?: bigint;
    name: string;
    type: string;
    readSpeed?: bigint;
    description: string;
    energyConsumption: bigint;
    endurance?: bigint;
    capacity: bigint;
    isSolidState?: boolean;
}): {
    id: bigint;
    manufacturer: string;
    writeSpeed: [] | [bigint];
    cacheSize: [] | [bigint];
    name: string;
    type: string;
    readSpeed: [] | [bigint];
    description: string;
    energyConsumption: bigint;
    endurance: [] | [bigint];
    capacity: bigint;
    isSolidState: [] | [boolean];
} {
    return {
        id: value.id,
        manufacturer: value.manufacturer,
        writeSpeed: value.writeSpeed ? candid_some(value.writeSpeed) : candid_none(),
        cacheSize: value.cacheSize ? candid_some(value.cacheSize) : candid_none(),
        name: value.name,
        type: value.type,
        readSpeed: value.readSpeed ? candid_some(value.readSpeed) : candid_none(),
        description: value.description,
        energyConsumption: value.energyConsumption,
        endurance: value.endurance ? candid_some(value.endurance) : candid_none(),
        capacity: value.capacity,
        isSolidState: value.isSolidState ? candid_some(value.isSolidState) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    totalPlayTime: bigint;
    preferredDifficulty?: string;
}): {
    name: string;
    totalPlayTime: bigint;
    preferredDifficulty: [] | [string];
} {
    return {
        name: value.name,
        totalPlayTime: value.totalPlayTime,
        preferredDifficulty: value.preferredDifficulty ? candid_some(value.preferredDifficulty) : candid_none()
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "singleCategory";
    singleCategory: string;
} | {
    __kind__: "categoryList";
    categoryList: Array<string>;
}): {
    singleCategory: string;
} | {
    categoryList: Array<string>;
} {
    return value.__kind__ === "singleCategory" ? {
        singleCategory: value.singleCategory
    } : value.__kind__ === "categoryList" ? {
        categoryList: value.categoryList
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Storage>): Array<_Storage> {
    return value.map((x)=>to_candid_Storage_n21(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
